pipeline:
  name: test
  identifier: test
  projectIdentifier: GitHarnessExp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.KalMiniKube
              namespace: safe-cracker-ns
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    connectorRef: account.ECS
                    image: safecrackerimg1
                    shell: Bash
                    command: cd orientation/safe-cracker && npm install
              - step:
                  type: Run
                  name: Build App
                  identifier: Build_App
                  spec:
                    connectorRef: account.ECS
                    image: safecrackerimg1
                    shell: Bash
                    command: cd orientation/safe-cracker && npm run build
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: account.ECS
                    region: us-east-1
                    account: "440716895683"
                    imageName: safecrackerimg1
                    tags:
                      - 0.0.1
                    baseImageConnectorRefs:
                      - account.harnessImage
                    context: orientation/safe-cracker/Dockerfile
  properties:
    ci:
      codebase:
        connectorRef: account.githubkalwebmail
        build: <+input>
